//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется BTR.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROJECTBAR                  103
#define IDR_MAINFRAME                   128
#define IDR_BTRTYPE                     129
#define IDD_ViewSize_Dlg                130
#define IDR_MENUPOP                     134
#define IDD_LoadStep_Dlg                135
#define IDD_Remn_Dlg                    136
#define IDD_Reion_Dlg                   137
#define IDD_Neutr_Dlg                   138
#define IDD_Res_Smooth                  139
#define IDD_IonSource_Dlg               140
#define IDD_Task_Dlg                    141
#define IDD_CommentsDlg                 142
#define IDD_Gas_Dlg                     143
#define IDD_MF_Dlg                      144
#define IDD_PLOT_Dlg                    145
#define IDD_PREVIEW_Dlg                 146
#define IDI_ICON_UP                     147
#define IDD_ASK_Dlg                     148
#define IDD_Inject_Dlg                  149
#define IDD_Surf_Dlg                    150
#define IDD_Fields_Dlg                  151
#define IDD_NBI_Dlg                     152
#define IDD_Beam_Dlg                    153
#define IDD_Beamlet                     154
#define IDD_Particles_Dlg               155
#define IDD_Thick_Dlg                   156
#define IDD_Thin_Dlg                    157
#define IDD_MPLOT_Dlg                   158
#define IDD_Threads_Dlg                 159
#define IDD_Contours_Dlg                160
#define IDD_RID_Dlg                     161
#define IDD_ATOM_Dlg                    162
#define IDD_Plasma_Dlg                  163
#define IDD_Num_DLG                     164
#define IDD_INPUT_DLG                   166
#define IDD_AddGas_Dlg                  167
#define IDD_START_DLG                   168
#define IDD_Limits_Dlg                  169
#define IDB_BITMAP1                     170
#define IDB_BITMAP2                     171
#define IDD_DefLoad_Dlg                 173
#define IDD_StatOptDlg                  175
#define IDC_Hor                         1000
#define IDC_Vert                        1001
#define IDC_StepX                       1002
#define IDC_StepY                       1003
#define IDC_X1                          1005
#define IDC_B1                          1006
#define IDC_X2                          1007
#define IDC_Percent                     1007
#define IDC_B2                          1008
#define IDC_Sigma                       1008
#define IDC_X3                          1009
#define IDC_Sigma1                      1009
#define IDC_B3                          1010
#define IDC_Default                     1010
#define IDC_Thin                        1011
#define IDC_Thick                       1012
#define IDC_Degree                      1013
#define IDC_Flat                        1014
#define IDC_Real                        1015
#define IDC_Tilt                        1016
#define IDC_Name                        1017
#define IDC_TASK                        1018
#define IDC_DATETIMEPICKER1             1019
#define IDC_DATETIMEPICKER2             1020
#define IDC_Comment                     1021
#define IDC_FILENAME                    1022
#define IDC_X                           1023
#define IDC_Pres                        1024
#define IDC_NEW                         1025
#define IDC_READFILE                    1026
#define IDC_Save                        1027
#define IDC_Bdata                       1028
#define IDC_COLUMNS                     1032
#define IDC_CAPTION                     1033
#define IDC_Text                        1035
#define IDC_Plot                        1036
#define IDC_LEFT                        1038
#define IDC_RIGHT                       1039
#define IDC_UP                          1040
#define IDC_DOWN                        1041
#define IDC_LIST_Quest                  1042
#define IDC_EDIT_ANSWER                 1043
#define IDC_FIT                         1044
#define IDC_Energy1                     1046
#define IDC_Te                          1052
#define IDC_Density                     1053
#define IDC_Rmajor                      1054
#define IDC_Rminor                      1055
#define IDC_Solid                       1057
#define IDC_Transparent                 1058
#define IDC_X4                          1062
#define IDC_Y1                          1063
#define IDC_Y2                          1064
#define IDC_Y3                          1065
#define IDC_Y4                          1066
#define IDC_Z1                          1067
#define IDC_Z2                          1068
#define IDC_Z3                          1069
#define IDC_Z4                          1070
#define IDC_MFON                        1071
#define IDC_MFOFF                       1072
#define IDC_Volt                        1073
#define IDC_MFcoeff                     1074
#define IDC_NeutrChannels               1075
#define IDC_GasON                       1075
#define IDC_RIDChannels                 1076
#define IDC_GasOFF                      1076
#define IDC_CalOpen                     1077
#define IDC_GasCoeff                    1077
#define IDC_CalClose                    1078
#define IDC_SINGAP                      1079
#define IDC_MAMuG                       1080
#define IDC_D                           1081
#define IDC_H                           1082
#define IDC_E                           1083
#define IDC_He                          1083
#define IDC_H3                          1084
#define IDC_RID                         1085
#define IDC_Li                          1085
#define IDC_Reion                       1086
#define IDC_Be                          1086
#define IDC_B                           1087
#define IDC_Plasma                      1088
#define IDC_C                           1088
#define IDC_Neutr                       1089
#define IDC_N                           1089
#define IDC_Reionisation                1090
#define IDC_O                           1090
#define IDC_BeamPlasma                  1091
#define IDC_Fe                          1091
#define IDC_Gauss                       1094
#define IDC_NonGauss                    1096
#define IDC_Beamlet                     1097
#define IDC_Particles                   1098
#define IDC_Xmin                        1108
#define IDC_Xmax                        1114
#define IDC_Help                        1120
#define IDC_Polar                       1131
#define IDC_Azimuth                     1132
#define IDC_Current                     1136
#define IDC_Energy                      1142
#define IDC_Mass                        1145
#define IDC_Time                        1147
#define IDC_Length                      1148
#define IDC_Tstep                       1154
#define IDC_Lstep                       1155
#define IDC_Npoints                     1158
#define IDC_Q                           1164
#define IDC_Nucl                        1165
#define IDC_Nbeamlets                   1169
#define IDC_Curr                        1170
#define IDC_PolarNStr                   1174
#define IDC_AzimNStr                    1175
#define IDC_Common                      1176
#define IDC_CoreDivHor                  1177
#define IDC_Individual                  1178
#define IDC_HaloDiv                     1179
#define IDC_HaloPart                    1180
#define IDC_CoreDivVert                 1183
#define IDC_CutoffCurr                  1187
#define IDC_NeutrGapIn                  1188
#define IDC_NeutrThickIn                1189
#define IDC_NeutrGapOut                 1190
#define IDC_NeutrThickout               1191
#define IDC_RIDGapIn                    1192
#define IDC_RIDGapOut                   1193
#define IDC_RIDThick                    1194
#define IDC_IonStepL                    1196
#define IDC_ATOMS                       1199
#define IDC_Step                        1203
#define IDC_SigmaNeutr                  1204
#define IDC_SigmaIon                    1205
#define IDC_Xlim                        1208
#define IDC_Neff                        1209
#define IDC_PosYield                    1210
#define IDC_Sort                        1212
#define IDC_TorCentreX                  1214
#define IDC_OptEl                       1216
#define IDC_OptIon                      1217
#define IDC_OptExch                     1219
#define IDC_Enhance                     1221
#define IDC_File                        1225
#define IDC_CalculWidth                 1226
#define ID_ReadAdd                      1227
#define IDC_Sigma2Strip                 1232
#define IDC_SigmaExch                   1233
#define IDC_RIDfile                     1234
#define IDC_IONPOWER                    1235
#define IDC_PROC                        1236
#define IDC_THREADS                     1237
#define IDC_NETADDRESS1                 1238
#define IDC_COLUMN1                     1239
#define IDC_COLUMN2                     1240
#define IDC_TorCentreY                  1241
#define IDC_TorCentreZ                  1242
#define IDC_BUTTON_Site                 1243
#define IDC_Level_Min                   1244
#define IDC_Level_Max                   1245
#define IDC_Level_Step                  1246
#define IDC_Level_Write                 1247
#define IDC_RIDcharge                   1249
#define IDC_EpsLimit                    1250
#define IDC_IterLimit                   1251
#define IDC_Eps                         1252
#define IDC_Iter                        1253
#define IDC_Calculate                   1255
#define IDC_Stop                        1256
#define IDC_Write                       1257
#define IDC_Nx                          1260
#define IDC_Ny                          1261
#define IDC_Ymin                        1264
#define IDC_Ymax                        1265
#define IDC_Zmin                        1266
#define IDC_Zmax                        1267
#define IDC_Reflect                     1268
#define IDC_PosX                        1269
#define IDC_PosY                        1270
#define IDC_PosZ                        1271
#define IDC_Vx                          1272
#define IDC_Vy                          1274
#define IDC_Vz                          1275
#define IDC_OptReion                    1276
#define IDC_CalcNeutr                   1277
#define IDC_CalcRID                     1278
#define IDC_CalcDuct                    1279
#define IDC_StepSpec                    1284
#define IDC_StepSpecR                   1285
#define IDC_Xspec0                      1286
#define IDC_XRspec0                     1287
#define IDC_Xspec1                      1291
#define IDC_XRspec1                     1292
#define IDC_Hw                          1293
#define IDC_Dw                          1294
#define IDC_Tw                          1295
#define IDC_Hew                         1296
#define IDC_Liw                         1297
#define IDC_Bew                         1298
#define IDC_Bw                          1299
#define IDC_Cw                          1300
#define IDC_Nw                          1301
#define IDC_Ow                          1302
#define IDC_Few                         1303
#define IDC_NTprofiles                  1304
#define IDC_PSI                         1305
#define IDC_Nsurf                       1306
#define IDC_SurfOptions                 1309
#define IDC_RADIO_Stand                 1310
#define IDC_RADIO_Free                  1311
#define IDC_MFfile                      1312
#define IDC_GasFile                     1313
#define IDC_GasFileName                 1314
#define IDC_MFFileName                  1315
#define IDC_MFadvBtn                    1316
#define IDC_GasAdvBtn                   1317
#define IDC_AddFileBUTTON               1318
#define IDC_Atom_Power                  1320
#define IDC_NegIon_Power                1322
#define IDC_PosIons_Power               1323
#define IDC_RADIO_New                   1325
#define IDC_RADIO_Results               1327
#define IDC_RADIO_Demo                  1328
#define IDC_Smin                        1331
#define IDC_Smax                        1332
#define IDC_Sstep                       1334
#define IDC_EDIT1                       1336
#define IDC_Lines                       1336
#define IDC_SigmaBase                   1336
#define IDC_RoundStep                   1337
#define IDC_OptN                        1339
#define IDC_OptStep                     1340
#define IDC_PosLoc                      1341
#define IDC_Afall                       1342
#define IDC_Power                       1343
#define IDC_PolFluxBtn                  1344
#define IDC_PosLoc2                     1344
#define IDC_PosGlob                     1344
#define IDC_BUTTON2                     1345
#define IDC_BUTTON3                     1346
#define IDC_PlotDecay                   1347
#define IDC_Parallel                    1349
#define IDC_RADIO3                      1350
#define IDC_Focused                     1350
#define IDC_Ray                         1351
#define IDC_Coord                       1352
#define IDC_RAD                         1353
#define IDC_Azim                        1355
#define IDC_CHECK1                      1356
#define IDC_AddDuct                     1356
#define ID_DATA_GET                     32771
#define ID_DATA_STORE                   32772
#define ID_VIEW_FITONOFF                32773
#define ID_VIEW_SIZE                    32774
#define ID_PLATE_PROPERTIES             32778
#define ID_PLATE_LOAD                   32779
#define ID_PLATE_SCALE                  32780
#define ID_PLATE_EMIT                   32782
#define ID_PLATE_CLEAR                  32783
#define ID_PLATE_SELECT                 32784
#define ID_STOP                         32785
#define ID_PLATE_DELETE                 32786
#define ID_OPTIONS_STOPIONSAFTERNEUTRALISER 32787
#define ID_OPTIONS_ACCOUNTOFREIONIZATION 32788
#define ID_OPTIONS_STOPREIONIZEDPARTICLES 32789
#define ID_OPTIONS_STRAYFIELDONOFF      32790
#define ID_OPTIONS_OPENCALORIMETER      32791
#define ID_TASKS_MAGSHIELD              32792
#define ID_TASKS_NEUTRALISATION         32793
#define ID_TASKS_REIONIZATION           32794
#define ID_PLATE_SAVE                   32795
#define ID_RESULTS_SMOOTH               32796
#define ID_PLATE_SMOOTH                 32797
#define ID_RESULTS_READ                 32798
#define ID_RESULTS_SAVEALL              32799
#define ID_DATA_DEFAULT                 32800
#define ID_DATA_ACTIVE                  32801
#define ID_VIEW_ZOOMBOX                 32802
#define ID_OPTIONS_REALIONSOURCESTRUCTURE 32803
#define ID_DATA_SAVE                    32804
#define ID_RESULTS_READALL              32805
#define ID_OPTIONS_DRAW                 32806
#define ID_OPTIONS_SINGAP               32807
#define ID_TASKS_RID                    32808
#define ID_START                        32813
#define ID_PLATE_SELECTALLPLATES        32814
#define ID_VIEW_FULLAREA                32816
#define ID_TASKS_OTHER                  32817
#define ID_VIEW_RID                     32818
#define ID_VIEW_NEUTRALISER             32819
#define ID_VIEW_FIELDS                  32820
#define ID_VIEW_NUMBERING               32821
#define ID_VIEW_BEAM                    32822
#define ID_EDIT_TITLE                   32823
#define ID_EDIT_COMMENTS                32824
#define ID_HELP_MANUAL                  32825
#define ID_EDIT_MAGFIELD                32826
#define ID_EDIT_GAS                     32827
#define ID_VIEW_PARTICLES               32828
#define ID_EDIT_MAGFIELD_7COLUMNS       32829
#define ID_EDIT_MAGFIELD_4COLUMNS       32830
#define ID_EDIT_MAGFIELD_OTHER          32831
#define ID_PLOT_BEAMLETCURR             32832
#define ID_PLOT_SINGAPARRAY             32833
#define ID_PLOT_SINGAPPOS               32834
#define ID_PLOT_GASPROFILE              32835
#define ID_PLOT_MAGNETICFIELD           32836
#define ID_PLOT_BEAMFOOT                32837
#define ID_PLOT_MAMUGPOSITIONS          32838
#define ID_PLOT_LOADMAP                 32839
#define ID_PLOT_3DLOAD                  32840
#define ID_PLOT_MAXPROFILES             32841
#define ID_PLOT_BEAMLETFOOT             32842
#define ID_PLATE_3DPLOT                 32843
#define ID_PLATE_ZOOMIN                 32844
#define ID_PLATE_ZOOMOUT                32845
#define ID_PLATE_MAXPROFILES            32846
#define ID_ASK                          32847
#define ID_TASKS_BEAMPLASMA             32848
#define ID_OPTIONS_TRACENEUTRALSINPLASMA 32849
#define ID_PLOT_PENETRATION             32852
#define ID_PLOT_NEUTREFFICIENCY         32853
#define ID_PLATE_CONTOURS               32854
#define ID_PLOT_CONTOURS                32855
#define ID_OPTIONS_SURFACES_ADD         32856
#define ID_OPTIONS_BEAM                 32857
#define ID_OPTIONS_NBICONFIG            32858
#define ID_OPTIONS_FIELDS               32859
#define ID_OPTIONS_SURFACES_ENABLEDISABLEALL 32860
#define ID_DATA_IMPORT_PDPSINGAP        32863
#define ID_TASKS_PDPCODE                32866
#define ID_RESULTS_PDPOUTPUT_TABLE      32867
#define ID_DATA_IMPORT_SINGAP           32870
#define ID_PDP_BEAMLETS                 32871
#define ID_DATA_EXPORT_PDPGEOM          32873
#define ID_DATA_EXPORT_REGULARBEAM      32874
#define ID_Parallel                     32875
#define ID_PLOT_RE                      32876
#define ID_SURFACES_SORTINCR            32877
#define ID_BUTTON32878                  32878
#define ID_A                            32879
#define ID_PLOT_COMBINE                 32880
#define ID_PLOT_COMBI                   32881
#define ID_PLATE_COMBINE                32882
#define ID_PLATE_CL                     32883
#define ID_PLATE_CLEARSELECT            32884
#define ID_EDIT_FIRSTWALL               32885
#define ID_FIRSTWALL_2DCONTOUR          32886
#define ID                              32887
#define ID_EDIT_FW_2D                   32888
#define ID_SEND_BTRINPUT                32889
#define ID_SEND_OTHER                   32890
#define ID_EDIT_PLASMA                  32891
#define ID_PLASMA_TE                    32892
#define ID_PLASMA_TENE                  32893
#define ID_PLOT_BEAMINPLASMA            32894
#define ID_BEAMINPLASMA_HORIZONTALPLANE 32895
#define ID_BEAMINPLASMA_VERTICALPLANE   32896
#define ID_DATA_SAVEADDSURF             32897
#define ID_DATA_READADDSURF             32898
#define ID_Menu                         32899
#define ID_Plasma_PSI                   32900
#define ID_TASKS_TRACE                  32901
#define ID_TRACEBIGPARTICLE_ATOM        32902
#define ID_TRACEBIGPARTICLE_ION         32903
#define ID_OPTIONS_PLASMA               32904
#define ID_RESULTS_SAVESUMMARY          32905
#define ID_GASPROFILE_X                 32906
#define ID_GASPROFILE_X32907            32907
#define ID_OPTIONS_INPUT                32908
#define ID_INPUT_FREE                   32909
#define ID_INPUT_STANDARD               32910
#define ID_SURFACES_READ                32911
#define ID_PLATE_MODIFYSURF             32917
#define ID_PLATE_DELETEALLFREE          32918
#define ID_PLATE_SHO                    32919
#define ID_PLATE_FILE                   32920
#define ID_PLOT_RE32921                 32921
#define ID_PLOT_REION                   32922
#define ID_OPTIONS_THREADS              32923
#define ID_PD_REIONS                    32924
#define ID_PD_ATOMS                     32925
#define ID_PLOT_ANGULARDISTR            32926
#define ID_NEUTRALIZATION_CURRENTS      32927
#define ID_NEUTRALIZATION_RATES         32928
#define ID_TRACEBIGPARTICLE_ELECTRON    32929
#define ID_DATA_LOG                     32930
#define ID_LOG_VIEW                     32931
#define ID_LOG_SAVE                     32932
#define ID_DATA_STATISTICS              32933
#define ID_STATISTICS_VIEW              32934
#define ID_STATISTICS_SET               32935
#define ID_SURFACES_STEPPREF            32936
#define ID_SURFACES_MESH                32937
#define ID_PLATE_LOADOPT                32938
#define ID_PLATE_CLEARALL               32939
#define ID_EDIT_CROSS                   32940

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32941
#define _APS_NEXT_CONTROL_VALUE         1357
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
